// Generated by cup-dieline.py - do not edit by hand.
export const CUPS = {
  "woodgrain-16oz-hot": { label: "16 oz Hot  (single wall paper)", topDia: 90.0, bottomDia: 60.0, height: 135.0 },
  "woodgrain-24oz-hot": { label: "24 oz Hot  (single wall paper)", topDia: 90.0, bottomDia: 60.0, height: 175.0 },
  "woodgrain-16oz-cold": { label: "16 oz Cold  (clear PET)", topDia: 95.0, bottomDia: 60.0, height: 132.0 },
  "woodgrain-24oz-cold": { label: "24 oz Cold  (clear PET)", topDia: 98.0, bottomDia: 60.0, height: 180.0 },
};
