// Generated by cup-dieline.py - do not edit by hand.
export const CUPS = {
  "woodgrain-12oz-hot": { label: "12 oz Hot  (single wall paper)", topDia: 90.0, bottomDia: 60.0, height: 105.0 },
  "woodgrain-16oz-hot": { label: "16 oz Hot  (single wall paper)", topDia: 90.0, bottomDia: 60.0, height: 135.0 },
  "woodgrain-16oz-cold": { label: "16 oz Cold  (clear PET)", topDia: 95.0, bottomDia: 60.0, height: 132.0 },
};
